name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build and run Unit and Architecture Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install adg
        run: go install github.com/adr/ad-guidance-tool/adg@latest

      - name: Install netarch plugin
        run: adg enforce plugin install netarch --repo github.com/phi42/ad-plugin-NetArchTest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate architecture tests from ADR rules
        run: adg enforce compile -i docs/architecture-decision-log/ -p netarch -o src/Tests/ArchTests/Generated/

      - name: Run build
        run: ./build.sh BuildAndUnitTests --configuration Release

  rule-check:
    name: Check Architecture File Rules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install adg
        run: go install github.com/adr/ad-guidance-tool/adg@latest

      - name: Install fscheck plugin
        run: adg enforce plugin install fscheck --repo github.com/phi42/ad-plugin-FScheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check architecture file rules
        run: adg enforce verify -i docs/architecture-decision-log/ -p fscheck -r src

  # integration:
  #   name: Build and run Integration Tests
  #   needs: [build]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 8.0.x
  #     - name: Run build
  #       run: ./build.sh RunAllIntegrationTests

